### ISSUE TITLE
Vagrant-Tramp does not support underscores

### ISSUE THREAD

**Issue by jmercouris** [dougm/vagrant-tramp#24]
Note: I have submitted a pull request for this issue.

If you make two folders:

machineOne
and
machine_two

Then, you place two identical vagrant files in each folder. Then you start both machines. You can ssh into machineOne and machine_two - BUT you cannot use vagrant-tramp with machine_two.

My guess is that there must be some parsing related to the usage of an underscore that is causing it to break. It looks for a machine with a title of machineOne_default: to connect to, and when it sees an underscore ahead of time, it breaks for example it probably tries to connect to machine_two: instead of machine_two_default:.

I have a strong feeling it is tied to the following lines (bin/vagrant-tramp-ssh):
read dir_name name <<<\
     $(echo $1 \
              | awk -F_ '{ print $1; print $2 }')
if [[ ! $name ]]; then name="default"; fi

**Comment by ryanprior** [comment]
I had some thoughts about this previously, but decided not to act yet since I didn't come up with anything foolproof and didn't want to break people's workflows multiple times.

* Slashes are disallowed in folder names, so perhaps they do make a better choice. However, I think they are allowed in VM names, in which case there could still be multiple slashes.
* One thing we could do that keeps close to the current behavior is to replace underscores with dashes, so that `machine_two` becomes `machine-two`, which works fine as long as you don't ALSO have a real actual folder called `machine-two`.
* Instead of using an underscore or slash, we could use a character which is very unlikely to be in the folder or VM name, giving us identifiers like `my-project§trusty`. As long as the user is okay with tab completion, this won't slow them down much because Emacs will write the § for them. For users who prefer to type the whole identifier out or need to use it in a context that doesn't support non-ASCII for some reason, this strategy sucks.
* We could allow for identifier collisions, appending the VM's unique ID to the end in cases where we detect a conflict. This gives the user something to work with even in that corner case while making it more predictable in the common case. (For example, our user who has both `machine_two` and `machine-two` could have identifiers `machine-two-aba4d3j`, `machine-two_VM1-11efb7a`, and `machine-two_VM2-f3f3d19`)
* We could institute an regime with escaping, creating unambiguous non-conflicting identifiers for every VM. This is a good concept, if perhaps more involved, but I question whether it belongs in `vagrant-tramp` or elsewhere. For example, it might be done as part of the work to make `vagrant` commands (including `global-status`) machine-readable. That way, the problem is solved for all `vagrant` users and tool integrators instead of having to grapple with it piecemeal all over the place.

**Comment by jmercouris** [comment]
I’m not sure exactly how to solve it, but I think that the best and simplest is probably the underscore to dash substitution, then you could do a dash to underscore substitution the other way around. Alternatively, you could write a more sophisticated awk parse in the bash script, I believe there is a way to write  a script that solves this problem without doing a bunch of magic- I just can’t think of how to do it.
